### ISSUE TITLE
install-dependencies example is old

### ISSUE THREAD

**Issue by mmurooka** [jrl-umi3218/github-actions#16]
The `install-dependencies` example in [README](https://github.com/jrl-umi3218/github-actions/tree/master/install-dependencies) uses bintray URL, which is not supported now.

**Comment by gergondet** [comment]
Hi @mmurooka 

That's a good point but the new multi-contact repos don't have publicly available keys (you'd need to provide a `key-uri` instead). Since the main purpose of the example is to show how one could add such a key maybe it's ok to leave it as is?

**Comment by mmurooka** [comment]
Thank you for the explanation. I think that's OK.
